// <auto-generated />
using System;
using Assurance.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assurance.Infrastructure.Migrations
{
    [DbContext(typeof(AssuranceContext))]
    partial class AssuranceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Assurance.ApplicationCore.Entites.AssuranceTardi", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePartenaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeRabais")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDeNaissance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstDiabetique")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstFumeur")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstHypertendu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PratiqueActivitePhysique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexe")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Solde")
                        .HasColumnType("REAL");

                    b.Property<bool>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Assurance");
                });
#pragma warning restore 612, 618
        }
    }
}
